
name: build docker image

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get latest release version number
        id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fradelg
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build multiarch image
        run: |
          docker buildx build --push \
            --tag fradelg/mysql-cron-backup:${{ steps.docker-tag.outputs.tag }} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
